#!/bin/bash
apt-get install -qq curl g++ make
curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz
cd spatialindex-src-1.8.5
./configure
make clean
make
make install
ldconfig
pip3 install rtree
cd ..
rm -r ./spatialindex-src-1.8.5
